# Generated by Django 2.1.4 on 2018-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0002_auto_20181213_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='slug',
            field=models.SlugField(default='item-name'),
        ),
    ]
