# Generated by Django 2.1.4 on 2018-12-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0003_vegetable_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='slug',
        ),
    ]
