# Generated by Django 2.1.4 on 2018-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0004_remove_vegetable_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='slug',
            field=models.SlugField(default='new-item'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='slug',
            field=models.SlugField(default='new-item'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='slug',
            field=models.SlugField(default='new-item'),
        ),
        migrations.AddField(
            model_name='users',
            name='slug',
            field=models.SlugField(default='new-user'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='slug',
            field=models.SlugField(default='new-item'),
        ),
    ]
