# Generated by Django 2.1.4 on 2018-12-06 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0004_auto_20181206_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 10, 19, 9, 25458)),
        ),
    ]
