# Generated by Django 2.1.4 on 2018-12-07 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0007_auto_20181207_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='email',
            field=models.EmailField(default='abc@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 11, 48, 33, 468493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
