# Generated by Django 2.1.4 on 2018-12-07 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0008_auto_20181207_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='John', max_length=20)),
                ('user_age', models.IntegerField(default=23)),
                ('user_email', models.EmailField(default='abc@email.com', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 13, 5, 24, 127118, tzinfo=utc)),
        ),
    ]
