# Generated by Django 2.1.4 on 2018-12-07 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0010_auto_20181207_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 14, 53, 7, 409890, tzinfo=utc)),
        ),
    ]
