# Generated by Django 2.1.4 on 2018-12-10 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0011_auto_20181207_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 6, 4, 0, 280336, tzinfo=utc)),
        ),
    ]
