# Generated by Django 2.1.4 on 2018-12-10 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0012_auto_20181210_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 8, 58, 27, 645564, tzinfo=utc)),
        ),
    ]
