# Generated by Django 2.1.4 on 2018-12-11 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0013_auto_20181210_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='slug',
            field=models.SlugField(default='new'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 15, 5, 53, 555207, tzinfo=utc)),
        ),
    ]
