# Generated by Django 2.1.4 on 2018-12-11 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('garyve', '0014_auto_20181211_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 15, 6, 46, 21772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='slug',
            field=models.SlugField(default='new-pro'),
        ),
    ]
